FROM golang:1.25.10-alpine3.23@sha256:8d22e29d960bc50cd025d93d5b7c7d220b1ee9aa7a239b3c8f55a57e987e8d45
ARG VERSION=not_versioned
ARG CYCLONEDX_GOLANG_VERSION=v1.9.0
RUN mkdir /app && mkdir /sbom
COPY . /app/
WORKDIR /app
RUN go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${CYCLONEDX_GOLANG_VERSION} \
    && cyclonedx-gomod version \
    && cyclonedx-gomod mod -type application -json -output bom.json . \
    && cp /app/bom.json /sbom/sbom.json
